### ISSUE TITLE
Coverage reports appear to not upload on windows

### ISSUE THREAD

**Issue by Cadair** [OpenAstronomy/azure-pipelines-templates#12]
i.e. https://dev.azure.com/sunpy/sunpy/_build/results?buildId=3608&view=logs&j=7073c21a-1e55-56ea-46de-8524ee585145&t=f2527250-f666-5be7-f464-0fc35397368d&l=48

**Comment by ConorMacBride** [comment]
Logs for that job are no longer available but [a recent SunPy job](https://dev.azure.com/sunpy/sunpy/_build/results?buildId=22698&view=logs&j=475592e9-b16d-5db7-f2c4-00d679a5e4fd&t=706d8b17-0f02-58db-8de2-8925beaed573) uploaded to codecov successfully. The codecov uploader has also been updated recently.
