### ISSUE TITLE
Building wheels with auditwheel and external libraries?

### ISSUE THREAD

**Issue by nabobalis** [OpenAstronomy/azure-pipelines-templates#22]
I was trying to build wheels for sunkit-image which requires an external dependency on fftw3 (https://github.com/sunpy/sunkit-image/pull/41) and was unable to pass through the libraries for it (which I can pass into for the tests).

I would also require auditwheel (https://github.com/pypa/auditwheel) to repair the wheel after creation. I see that cibuildwheels in the last version has added support for calling repair but I would need to still be able to install libraries at the publish stage. 

Is this possible right now or something that would need to be added?

**Comment by Cadair** [comment]
FTR, this is supported in cibuildwheel and just works "like magic".
