### ISSUE TITLE
Add some quick exit thing for [ci skip]?

### ISSUE THREAD

**Issue by Cadair** [OpenAstronomy/azure-pipelines-templates#38]
We could add something here which insta-passes the build if `[ci skip]` etc are in the commit message? We could even add the ability to have an individual skip for each build?

**Comment by astrofrog** [comment]
Sound good to me, though I'm not sure what you mean about for each build - would there be some kind of syntax to use for that? Implementing the simple ``[ci skip]`` and maybe ``['azure skip]`` would be enough initially.

**Comment by Cadair** [comment]
fixed in #74
