### ISSUE TITLE
Is conda really necessary?

### ISSUE THREAD

**Issue by pllim** [OpenAstronomy/azure-pipelines-templates#43]
Why use conda?

**Comment by astrofrog** [comment]
We don't use conda unless opted-in with the ``-conda`` environment factor. I don't understand why the windows build in extension helpers was using conda :thinking:

**Comment by astrofrog** [comment]
And we do want to allow conda as opt-in as there are cases where it can be useful (but we definitely don't want it by default!)

**Comment by pllim** [comment]
Okay then. The 2-space indentation is hard to read, my bad. Looks the the Windows failure went away by itself, so not conda's fault (this time). Sorry for the noise!
