### ISSUE TITLE
Wrong conditional statement in documentation

### ISSUE THREAD

**Issue by epassaro** [OpenAstronomy/azure-pipelines-templates#57]
The following statement from the [documentation](https://openastronomy-azure-pipelines.readthedocs.io/en/latest/publish.html#usage-and-options) does not work. 

```
    ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags/v') }}:
```

Need to be replaced with this.

```
    ${{ if startsWith(variables.Build.SourceBranch, 'refs/tags/v') }}:
```

**Comment by Cadair** [comment]
What error did you run into with it, we seem to be using it fine with sunpy: https://github.com/sunpy/sunpy/blob/master/azure-pipelines.yml#L90

I think either should be valid.

**Comment by Cadair** [comment]
Oh that is probably #53
